services:
  db:
    image: postgres:15
    container_name: alzheimer_db
    restart: always
    environment:
      POSTGRES_USER: neuro_user
      POSTGRES_PASSWORD: neuro_password
      POSTGRES_DB: neurocast_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
