import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const thmanyah = localFont({
  src: "../../public/fonts/thmanyahseriftext-Regular.woff2",
  variable: "--font-thmanyah",
  display: "swap",
});

export const metadata: Metadata = {
  title: "NeuroCast",
  description: "Generated by Ali ALshehri",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${thmanyah.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
